<form class="form-horizontal">
        <ul>
            <? foreach ($this->berufsbilder as $berufsbild) {?>

               <li>
                   <a href="?controller=berufsbild&action=edit&id=<?= $berufsbild->getId() ?>"> <?= $berufsbild->getBerufsbild() ?> </a>
                </li>

            <? } ?>
        </ul>
        <div class="btn"><a href="?controller=berufsbild&action=add">Neues Berufsbild</a></div>

</form>