<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="Style/Style.css">
    </head>
    <body>
        <ul>
            <?php foreach ($this->funktionen as $funktion) { ?>

                <li>
                    <a href="?controller=funktion&action=edit&id=<?= $funktion->getId() ?>"> <?= $funktion->getFunktion() ?> </a>
                </li>

            <?php } ?>
        </ul>
    </body>
</html>