<form class="form-horizontal">

    <table>
        <thead>
            <tr>
                <th>
                    &nbsp;
                </th>
                <th>
                    Name
                </th>
                <th>
                    Abteilung
                </th>
                <th>
                    Von
                </th>
                <th>
                    Bis
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->einteilungen as $einteilung) { ?>
                <? if ($_GET['id'] == $einteilung->getId()) { ?>
                    <tr>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            <?= $einteilung->getPerson()->getVorname() . ' ' . $einteilung->getPerson()->getNachname() ?>
                        </td>
                        <td>
                            <?= $einteilung->getAbteilung()->getAbteilung() ?>
                        </td>
                        <td>
                            KW<?= $einteilung->getVonKalenderwoche() . ' ' . $einteilung->getVonJahr() ?>
                        </td>
                        <td>
                            KW<?= $einteilung->getBisKalenderwoche() . ' ' . $einteilung->getBisJahr() ?>
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=edit&id=<?= $einteilung->getId() ?>"><img src="Style/Icons/edit.png"></a>
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=delete&id=<?= $einteilung->getId() ?>"><img src="Style/Icons/delete.png"></a>
                        </td>
                    </tr>            
                <? } else { ?>
                    <tr>
                        <td>
                            <input id="cb<?= $einteilung->getId() ?>" name="cb<?= $einteilung->getId() ?>" type="checkbox">
                        </td>
                        <td>
                            <?= $einteilung->getPerson()->getVorname() . ' ' . $einteilung->getPerson()->getNachname() ?>
                        </td>
                        <td>
                            <?= $einteilung->getAbteilung()->getAbteilung() ?>
                        </td>
                        <td>
                            KW<?= $einteilung->getVonKalenderwoche() . ' ' . $einteilung->getVonJahr() ?>
                        </td>
                        <td>
                            KW<?= $einteilung->getBisKalenderwoche() . ' ' . $einteilung->getBisJahr() ?>
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=edit&id=<?= $einteilung->getId() ?>"><img src="Style/Icons/edit.png"></a>
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=delete&id=<?= $einteilung->getId() ?>"><img src="Style/Icons/delete.png"></a>
                        </td>
                    </tr>

                <? }
            } ?>

        </tbody>
    </table>

</form>

