<form class="form-horizontal">

    <table>
        <thead>
            <tr>
                <th>
                    &nbsp;
                </th>
                <th>
                    Vorname
                </th>
                <th>
                    Nachname
                </th>
                <th>
                    Abteilung
                </th>
                <th>
                    Von Kalenderwoche
                </th>
                <th>
                    Von Jahr
                </th>
                <th>
                    Bis Kalenderwoche
                </th>
                <th>
                    Bis Jahr
                </th>
                <th>
                    &nbsp;
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->einteilungen as $einteilung) { ?>
                <? if ($_GET['id'] == $einteilung->getId()) { ?>
                    <tr>
                        <td>
                            &nbsp;
                        </td>
                        <td>
                            <input id="txtVorname" name="txtVorname" type="text" maxlength="20" value="<?= $einteilung->getPerson()->getVorname(); ?>">
                        </td>
                        <td>
                            <input id="txtNachname" name="txtNachname" type="text" maxlength="20" value="<?= $einteilung->getPerson()->getNachname(); ?>">
                        </td>
                        <td>

                            <select name="ddlAbteilung" size="1">
                                <? foreach ($this->abteilungen as $abteilung) { ?>
                                    <option value="<?= $abteilung->getId() ?>" <? echo (($einteilung->getAbteilung()->getId() == $abteilung->getId()) ? "selected=\"selected\"" : "") ?>>
                                        <?= $abteilung->getAbteilung() ?></option>
                                <? } ?>
                            </select>

                        </td>

                        <td>
                            <input id="txtVonKalenderwoche" name="txtVonKalenderwoche" type="text" maxlength="2" size="2" value="<?= $einteilung->getVonKalenderwoche() ?>">
                        </td>
                        <td>
                            <input id="txtVonJahr" name="txtVonJahr" type="text" maxlength="4" size="4" value="<?= $einteilung->getVonJahr() ?>">
                        </td>
                        <td>
                            <input id="txtBisKalenderwoche" name="txtBisKalenderwoche" type="text" maxlength="2" size="2" value="<?= $einteilung->getBisKalenderwoche() ?>">
                        </td>
                        <td>
                            <input id="txtBisJahr" name="txtBisJahr" type="text" maxlength="4" size="4" value="<?= $einteilung->getBisJahr() ?>">
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=save"><img src="Style/Icons/save.png"></a>
                        </td>
                    </tr>            
                <? } else { ?>
                    <tr>
                        <td>
                            <input id="cb<?= $einteilung->getId() ?>" name="cb<?= $einteilung->getId() ?>" type="checkbox">
                        </td>
                        <td>
                            <?= $einteilung->getPerson()->getVorname() ?>
                        </td>
                        <td>
                            <?= $einteilung->getPerson()->getNachname() ?>
                        </td>
                        <td>
                            <?= $einteilung->getAbteilung()->getAbteilung() ?>
                        </td>
                        <td>
                            <?= $einteilung->getVonKalenderwoche() ?>
                        </td>
                        <td>
                            <?= $einteilung->getVonJahr() ?>
                        </td>
                        <td>
                            <?= $einteilung->getBisKalenderwoche() ?>
                        </td>
                        <td>
                            <?= $einteilung->getBisJahr() ?>
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=edit&id=<?= $einteilung->getId() ?>"><img src="Style/Icons/edit.png"></a>
                        </td>
                        <td>
                            <a href="?controller=einteilung&action=delete&id=<?= $einteilung->getId() ?>"><img src="Style/Icons/delete.png"></a>
                        </td>
                    </tr>

                    <?
                }
            }
            ?>

        </tbody>
    </table>

</form>

